spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp_customer?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

logging:
  level:
    com.jumbosoft.erpcustomer: INFO
